services:
    - docker

language: minimal

os:
    - linux

before_install:
    - source ./.travis/setup.sh

# script:
   # - ./.travis/run.sh

deploy:
- provider: script
  script: /bin/bash .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    tags: true
